### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by DanBurkhardt** [bwilkie/Chat-AI---Runs-in-Python#1]
can you please provide a requirements.txt file that also includes any specific versions of dependencies. and please also indicate which version of python is required as well for the python env.

**Comment by bwilkie** [comment]
Built with Python 3.8.18 and the requirements file has been uploaded. If you dont have the matching cuda you may want to set n_gpu_layers to 0

**Comment by DanBurkhardt** [comment]
I do have CUDA, should be good-- thanks for the additional support, will check out the latest later today.

**Comment by bwilkie** [comment]
No probs. Feel free to reach out with any questions or share what you create!
